artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_dataset: conll2003
  dataset: artifacts/data_ingestion/dataset

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test","validation"]
  
    
